Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/pages_controller.rb
app/models/user.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
app/views/layouts/application.html.erb
config/environments/development.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20230822163136_devise_create_users.rb
db/schema.rb
test/models/user_test.rb

I installed devise gem and tried to set it up.... After, I generated the user model and tried to configure it. I think i did a poor job but ill wait for your reviews. Thanks!!!

devise gem and user model

---

app/controllers/pages_controller.rb
config/routes.rb

Home action is now up and running, I tested the view. Lewis you can start front end on it.

added root route and user_auth exception to homepage

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss
app/views/layouts/application.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb
db/migrate/20230822205532_drop_boats_table.rb
db/migrate/20230822210748_drop_booking_table.rb

I have added the navbar and footer, let me know what you think! The first conflict is just that I added a semi colon at the end of boat_card and all the other conflicts are changing the code it came with as standard to match the views I coded.

navbar and footer added

---

app/views/shared/_navbar.html.erb

login-logout finished

---

app/models/user.rb

just made the user omniauthable

changed user model to omniauthable

---

app/controllers/bookings_controller.rb
app/views/bookings/new.html.erb
config/routes.rb

booking form added

---

Gemfile
Gemfile.lock
app/controllers/users/omniauth_callbacks/registrations_controller.rb
app/models/user.rb
app/views/devise/registrations/new.html.erb
config/application.rb
config/initializers/devise.rb
db/migrate/20230824194438_add_uid_to_users.rb
db/schema.rb

Created new column on users table + coded user model accordingly to the new field on users table

I hope this thing is finnally working

---

app/models/user.rb
db/schema.rb

just some random fixes

---

app/views/bookings/new.html.erb
config/database.yml

heroku configurations on database.yaml

some heroku postgres config

---

app/controllers/users/omniauth_callbacks/omniauth_callbacks_controller.rb

more heroku stuff to facebook login

more heriku configurations

---

app/controllers/boats_controller.rb
app/views/boats/edit.html.erb
app/views/boats/my_boats.html.erb
app/views/boats/new.html.erb
app/views/boats/show.html.erb
app/views/pages/home.html.erb
app/views/shared/_boatcard.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb

Changed some files, created others..... i hope you like it. cya tomorrow.

had no sleep today

---

Gemfile
app/controllers/boats_controller.rb
app/views/boats/edit.html.erb
app/views/boats/my_boats.html.erb
app/views/boats/show.html.erb

created some buttons on the show page, added @tinydancer96 delete button to it. Did some styling on the cards grid

some buttons on show and row styling

---

app/views/boats/my_boats.html.erb
app/views/boats/show.html.erb
config/routes.rb

button booking and some  routes file changes

booking button on show

---

app/assets/stylesheets/config/_colors.scss
app/models/user.rb
app/views/pages/home.html.erb
app/views/shared/_footer.html.erb
config/environments/production.rb
db/seeds.rb

The footer now sticks to the bottom, I tried to find a color for the logo to better contrast with the photo, please change it if you dont like. Also started heroku config to deal with image uploads.

set footer to page bottom + logo color + heroku active storage config

---

app/controllers/bookings_controller.rb
app/controllers/reviews_controller.rb
app/mailers/booking_notification_mailer.rb
app/views/booking_notification_mailer/booking_notification.html.erb
app/views/bookings/show.html.erb
config/environments/development.rb
config/environments/production.rb
test/mailers/booking_notification_mailer_test.rb
test/mailers/previews/booking_notification_mailer_preview.rb

defined booking_notification method on Mailer ### created action booking_notification on bookings controller after saving booking #### created view with email content ##### added setup to development and production environments

implemented mailer when booking action

---

app/views/bookings/show.html.erb

deleting buttons

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_search_bar.scss
app/controllers/boats_controller.rb
app/views/pages/home.html.erb
app/views/shared/_search_bar.html.erb

Search bar added to home page. Calendar doesn't currently make any difference to the sorting of boats.

Search bar for cities. Dates option there for demo purpose

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_booking_form.scss
app/views/bookings/new.html.erb

booking-form completed

---

app/assets/stylesheets/components/_footer.scss
app/views/boats/index.html.erb
app/views/bookings/edit.html.erb
app/views/bookings/new.html.erb
db/schema.rb

Finished edit form, changed font color for index page and footer links

Finished edit booking form

---

app/views/shared/_footer.html.erb

footer no longer sticky

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_boatcard.scss
app/assets/stylesheets/components/_booking_form.scss
app/assets/stylesheets/components/_index.scss
app/views/boats/index.html.erb
app/views/bookings/index.html.erb
app/views/shared/_boatcard.html.erb
db/migrate/20230902110443_remove_image_file_path_from_boats.rb
db/schema.rb
db/seeds.rb
lib/tasks/cache_clearing.rake

Changes in seed file to use cloudinary when seeding with photo resize, removed image_filepath from boats table

seed with cludinary, seed images resized to uniform

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

I have added a "Hello username" when logged in and just put a font awesome logo in place of an avatar

username and avatar finished

---

app/views/boats/index.html.erb
app/views/shared/_boatcard.html.erb
db/seeds.rb

Photo resize implemented on display to work on seed and form sbmitt

simplified seed code and implemented photo resize on display

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_boatcard.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/config/_fonts.scss
app/views/boats/index.html.erb
app/views/shared/_boatcard.html.erb
db/seeds.rb

styling on index cards and index map

styling index cards

---

app/javascript/controllers/flatpickr_controller.js
app/views/shared/_search_bar.html.erb

Search bar automatically switches to checkout date when check in selected

Search bar automatically switches to checkout date when check in

---

app/views/shared/_navbar.html.erb

trying to make this thing work for @tinydancer96  presentation 😒😁

commented out one line in _navbar
